### PR TITLE
Allow selecting values containing NUL byte

### PR DESCRIPTION
**Pull request by singpolyma**
Instead of truncating the string at the NUL byte, push the whole string to lua based on length.

### CODE REVIEW

**Comment by Zash** [comment]
Applicable to the other drivers?

**Comment by sparked435** [comment]
@Zash I would think so, but - tried to implement this in Postgres just now, the database (or possibly libpq) seems to silently truncate the string at the null character. Even after I modified statement_execute() to set a value length.

Apparently it's a known Postgres limitation. https://www.commandprompt.com/blog/null-characters-workarounds-arent-good-enough/

**Comment by singpolyma** [comment]
@sparked435 is this for postgres `TEXT` type? I would expect their `BLOB` type can handle NUL right? In sqlite there are no types so it was all kind of the same difference

**Comment by singpolyma** [comment]
I'd avoid VARCHAR in postgres, but yeah I'm not surprised if postgres VARCHAR or TEXT can't support non-text data. Since lua doesn't have a type for text technically they are all BLOB but I can see how you might not want to do it that way. Though for select queries does this matter? The type will be determined by the schema which may be created some other way, the main thing is if selecting from an existing blob column does it work?

**Pull request merged**
